# onnx operators
ADD = "Add"
CONV = "Conv"
BATCH_NORM = "BatchNormalization"
RELU = "Relu"
MAXPOOL = "MaxPool"
GLOBALAVERAGEPOOL = "GlobalAveragePool"
AVERAGE_POOL = "AveragePool"
PAD = "Pad"
FLATTEN = "Flatten"
GEMM = "Gemm"
DROPOUT = "Dropout"
RESHAPE = "Reshape"
CLIP = "Clip"
REDUCE_MEAN = "ReduceMean"

# o2p
O2P_COPY = "o2p_copy"
O2P_LOAD = "o2p_load"
O2P_STORE = "o2p_store"
O2P_GRAPH_HEAD = "o2p_graph_head"
